/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tindahan;

/**
 *
 * @author User
 */
public class COFE extends javax.swing.JFrame {

    /**
     * Creates new form COFE
     */
    public COFE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        radStick = new javax.swing.JRadioButton();
        radBlack = new javax.swing.JRadioButton();
        rad3N1 = new javax.swing.JRadioButton();
        chkPan = new javax.swing.JCheckBox();
        chkEGG = new javax.swing.JCheckBox();
        chkChoco = new javax.swing.JCheckBox();
        btnENTER = new javax.swing.JButton();
        btnCLEAR = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTAX = new javax.swing.JTextField();
        txtSUB = new javax.swing.JTextField();
        txtTOTAL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("     COFFEE");

        radStick.setText("STICK          5");
        radStick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStickActionPerformed(evt);
            }
        });

        radBlack.setText("BLACK         10");
        radBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBlackActionPerformed(evt);
            }
        });

        rad3N1.setText("3N1             15");
        rad3N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3N1ActionPerformed(evt);
            }
        });

        chkPan.setText("PANDESAL    3");
        chkPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPanActionPerformed(evt);
            }
        });

        chkEGG.setText("EGG BREAD    4");
        chkEGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEGGActionPerformed(evt);
            }
        });

        chkChoco.setText("CHOCOLANAY   5");
        chkChoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChocoActionPerformed(evt);
            }
        });

        btnENTER.setText("ENTER");
        btnENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENTERActionPerformed(evt);
            }
        });

        btnCLEAR.setText("CLEAR");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });

        btnEXIT.setText("EXIT");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });

        jLabel2.setText("CASH ON HAND");

        jLabel3.setText("SUB TOTAL");

        jLabel4.setText("CHANGE");

        txtTAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTAXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTAX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEXIT)
                    .addComponent(btnCLEAR)
                    .addComponent(btnENTER))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radStick, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radBlack)
                            .addComponent(rad3N1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkChoco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkEGG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkPan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkPan)
                                .addGap(18, 18, 18)
                                .addComponent(chkEGG)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radStick)
                                .addGap(18, 18, 18)
                                .addComponent(radBlack)
                                .addGap(19, 19, 19)))
                        .addComponent(chkChoco))
                    .addComponent(rad3N1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtTAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCLEAR)
                    .addComponent(jLabel3)
                    .addComponent(txtSUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEXIT)
                    .addComponent(jLabel4)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBlackActionPerformed
if (radBlack.isSelected())
           radStick.setSelected(false);
           rad3N1.setSelected(false);// TODO add your ha        // TODO add your handling code here:
    }//GEN-LAST:event_radBlackActionPerformed

    private void rad3N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3N1ActionPerformed
if (rad3N1.isSelected())
           radBlack.setSelected(false);
           radStick.setSelected(false);// TODO add your ha        // TODO add your handling code here:
    }//GEN-LAST:event_rad3N1ActionPerformed

    private void chkPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPanActionPerformed
if (chkPan.isSelected())
           chkEGG.setSelected(false);
           chkChoco.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_chkPanActionPerformed

    private void chkChocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChocoActionPerformed
if (chkChoco.isSelected())
           chkEGG.setSelected(false);
           chkPan.setSelected(false);        // T        // TODO add your handling code here:
    }//GEN-LAST:event_chkChocoActionPerformed

    private void radStickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radStickActionPerformed
        if (radStick.isSelected())
           radBlack.setSelected(false);
           rad3N1.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_radStickActionPerformed

    private void chkEGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEGGActionPerformed
if (chkEGG.isSelected())
           chkPan.setSelected(false);
           chkChoco.setSelected(false);        // T        // TODO add your handling code here:
    }//GEN-LAST:event_chkEGGActionPerformed

    private void txtTAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTAXActionPerformed

    private void btnENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENTERActionPerformed
        // TODO add your handling code here:
        
            double total;
            double subtotal =0;
            final double TAXRATE =0;
            double tax;
            
            if (radStick.isSelected()){
                
                subtotal = subtotal + 5;
            }else if (radBlack.isSelected()){
                subtotal = subtotal + 10;
            }else if (rad3N1.isSelected()){
                subtotal = subtotal + 15;
            }
            
            if (chkPan.isSelected()){
                subtotal = subtotal + 3;
            }else if (chkEGG.isSelected()){
                subtotal = subtotal + 4;
            }else if (chkChoco.isSelected()){
                subtotal = subtotal + 5;
            }
            txtSUB.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(txtSUB.getText());
       //quantity = Double.parseDouble(txtQNT.getText());
       //quantity = Integer.parseInt(txtQNT.getText());
        tax = Integer.parseInt(txtTAX.getText());
        
        total = subtotal - tax;
        
        txtTAX.setText(Double.toString(tax));
        
        txtTOTAL.setText(Double.toString(total));
    }//GEN-LAST:event_btnENTERActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
          System.exit(0); 
    }//GEN-LAST:event_btnEXITActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        // TODO add your handling code here:
         radStick.setSelected(false);
         radBlack.setSelected(false);
          rad3N1.setSelected(false);
           chkPan.setSelected(false);
            chkEGG.setSelected(false);
             chkChoco.setSelected(false);
             txtTOTAL.setText("");
             txtSUB.setText("");
             txtTAX.setText("");
             
    }//GEN-LAST:event_btnCLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new COFE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnENTER;
    private javax.swing.JButton btnEXIT;
    private javax.swing.JCheckBox chkChoco;
    private javax.swing.JCheckBox chkEGG;
    private javax.swing.JCheckBox chkPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rad3N1;
    private javax.swing.JRadioButton radBlack;
    private javax.swing.JRadioButton radStick;
    private javax.swing.JTextField txtSUB;
    private javax.swing.JTextField txtTAX;
    private javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
